### PR TITLE
CI changes and dependency bumps

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
- update `.drone.star` to latest from activity app
- update code-style to v4
- update other dependencies
```
  - Upgrading dasprid/enum (1.0.3 => 1.0.4): Extracting archive
  - Upgrading khanamiryan/qrcode-detector-decoder (1.0.5.2 => 1.0.6): Extracting archive
```

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUITwoFactTOTP-master-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/twofactor_totp/2241/12

**Review by SwikritiT — APPROVED** [review]

**Comment by SwikritiT** [comment]
@phil-davis CI is red here

**Comment by phil-davis** [comment]
> @phil-davis CI is red here

needs investigation - one of the other dependency bumps might be making tests fail.

**Comment by phil-davis** [comment]
`qrcode-detector-decoder` is used in tests. `1.0.6` has some problem/difference. I pinned that to `1.0.5.2` (the version that we already use)

**Pull request merged**
