### PR TITLE
Bye bye Travis

### PR DESCRIPTION
**Pull request by phil-davis**
All CI jobs are in drone now

### CODE REVIEW

**Comment by phil-davis** [comment]
There is a ``.drone.yml`` already in master. Why doesn't a drone job appear?

**Comment by karakayasemi** [comment]
@phil-davis please also remove Travis badge from the readme. Thanks.

**Comment by phil-davis** [comment]
This is waiting for travis-ci required to be turned off and drone required to be turned on for this repo

**Comment by phil-davis** [comment]
I will look...

**Comment by DeepDiver1975** [comment]
> I will look...

codecov step is missing ...

**Comment by phil-davis** [comment]
@DeepDiver1975 codecov upload:
https://drone.owncloud.com/owncloud/twofactor_totp/14/60
```
2018/11/02 07:47:54 you must provide a token
```
do you set that up for the repo?

**Comment by DeepDiver1975** [comment]
> do you set that up for the repo?

wil do ...

**Comment by phil-davis** [comment]
@DeepDiver1975 please review - I think all is good now.

**Pull request merged**
