### PR TITLE
Add php 7.2

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by karakayasemi** [comment]
Scrutinizer tired of waiting for Travis :)

**Comment by DeepDiver1975** [comment]
> Scrutinizer tired of waiting for Travis :)
> Merge state

and travis tired of mysql ...

````
$ mysql -u root -e "CREATE USER 'travis'@'localhost'"

ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'travis'@'localhost'

The command "mysql -u root -e "CREATE USER 'travis'@'localhost'"" failed and exited with 1 during .

**Comment by karakayasemi** [comment]
Why are we creating a MySQL user for the SQLite test? I didn't understand the yml file. Do we really need this MySQL user creation lines? I also do not understand why the command got an error :)

**Comment by DeepDiver1975** [comment]
> I also do not understand why the command got an error :)

I guess the travis image changed and a different user shall be used for accessing the mysql server.

**Comment by DeepDiver1975** [comment]
> Why are we creating a MySQL user for the SQLite test?

no idea - kill then? Feel free to take over

**Comment by karakayasemi** [comment]
> no idea - kill then? Feel free to take over
I will try to take care.

**Pull request merged**
